// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: cache_v2.proto

package savev2proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type V2Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataSize  uint32                 `protobuf:"varint,1,opt,name=metadata_size,json=metadataSize,proto3" json:"metadata_size,omitempty"`
	StringsSize   uint32                 `protobuf:"varint,2,opt,name=strings_size,json=stringsSize,proto3" json:"strings_size,omitempty"`
	ZonesSize     uint32                 `protobuf:"varint,3,opt,name=zones_size,json=zonesSize,proto3" json:"zones_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V2Header) Reset() {
	*x = V2Header{}
	mi := &file_cache_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V2Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V2Header) ProtoMessage() {}

func (x *V2Header) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V2Header.ProtoReflect.Descriptor instead.
func (*V2Header) Descriptor() ([]byte, []int) {
	return file_cache_v2_proto_rawDescGZIP(), []int{0}
}

func (x *V2Header) GetMetadataSize() uint32 {
	if x != nil {
		return x.MetadataSize
	}
	return 0
}

func (x *V2Header) GetStringsSize() uint32 {
	if x != nil {
		return x.StringsSize
	}
	return 0
}

func (x *V2Header) GetZonesSize() uint32 {
	if x != nil {
		return x.ZonesSize
	}
	return 0
}

type StringsTableV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Streets       []string               `protobuf:"bytes,2,rep,name=streets,proto3" json:"streets,omitempty"`
	HouseNumbers  []string               `protobuf:"bytes,3,rep,name=house_numbers,json=houseNumbers,proto3" json:"house_numbers,omitempty"`
	Cities        []string               `protobuf:"bytes,4,rep,name=cities,proto3" json:"cities,omitempty"`
	Regions       []string               `protobuf:"bytes,5,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringsTableV2) Reset() {
	*x = StringsTableV2{}
	mi := &file_cache_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringsTableV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringsTableV2) ProtoMessage() {}

func (x *StringsTableV2) ProtoReflect() protoreflect.Message {
	mi := &file_cache_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringsTableV2.ProtoReflect.Descriptor instead.
func (*StringsTableV2) Descriptor() ([]byte, []int) {
	return file_cache_v2_proto_rawDescGZIP(), []int{1}
}

func (x *StringsTableV2) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *StringsTableV2) GetStreets() []string {
	if x != nil {
		return x.Streets
	}
	return nil
}

func (x *StringsTableV2) GetHouseNumbers() []string {
	if x != nil {
		return x.HouseNumbers
	}
	return nil
}

func (x *StringsTableV2) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *StringsTableV2) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_cache_v2_proto protoreflect.FileDescriptor

const file_cache_v2_proto_rawDesc = "" +
	"\n" +
	"\x0ecache_v2.proto\x12\x12cachesaver.save.v2\"q\n" +
	"\bV2Header\x12#\n" +
	"\rmetadata_size\x18\x01 \x01(\rR\fmetadataSize\x12!\n" +
	"\fstrings_size\x18\x02 \x01(\rR\vstringsSize\x12\x1d\n" +
	"\n" +
	"zones_size\x18\x03 \x01(\rR\tzonesSize\"\x97\x01\n" +
	"\x0eStringsTableV2\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\x18\n" +
	"\astreets\x18\x02 \x03(\tR\astreets\x12#\n" +
	"\rhouse_numbers\x18\x03 \x03(\tR\fhouseNumbers\x12\x16\n" +
	"\x06cities\x18\x04 \x03(\tR\x06cities\x12\x18\n" +
	"\aregions\x18\x05 \x03(\tR\aregionsB\x0fZ\r./savev2protob\x06proto3"

var (
	file_cache_v2_proto_rawDescOnce sync.Once
	file_cache_v2_proto_rawDescData []byte
)

func file_cache_v2_proto_rawDescGZIP() []byte {
	file_cache_v2_proto_rawDescOnce.Do(func() {
		file_cache_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_v2_proto_rawDesc), len(file_cache_v2_proto_rawDesc)))
	})
	return file_cache_v2_proto_rawDescData
}

var file_cache_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cache_v2_proto_goTypes = []any{
	(*V2Header)(nil),       // 0: cachesaver.save.v2.V2Header
	(*StringsTableV2)(nil), // 1: cachesaver.save.v2.StringsTableV2
}
var file_cache_v2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_v2_proto_init() }
func file_cache_v2_proto_init() {
	if File_cache_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_v2_proto_rawDesc), len(file_cache_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cache_v2_proto_goTypes,
		DependencyIndexes: file_cache_v2_proto_depIdxs,
		MessageInfos:      file_cache_v2_proto_msgTypes,
	}.Build()
	File_cache_v2_proto = out.File
	file_cache_v2_proto_goTypes = nil
	file_cache_v2_proto_depIdxs = nil
}
