linters:
  enable:
    - revive
    #- exhaustruct
    - nakedret
    - gomoddirectives
    - importas
    - misspell
    - promlinter
    - prealloc
    - predeclared
    - stylecheck
    - errcheck
  disable:
    - ineffassign

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
        disabled: true
  staticcheck:
    checks:
      - "-SA4006"
  gosimple:
    checks:
      - "-S1002"
  exhaustruct:
    include:
      - ".*Service"
      - ".*Server.*"
    exclude:
      - ".*mutex"
      - ".*mutex"
  stylecheck:
    checks:
      - "-ST1003"
