// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: cache.proto

package saveproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheHeader struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MetadataSize     uint32                 `protobuf:"varint,1,opt,name=metadata_size,json=metadataSize,proto3" json:"metadata_size,omitempty"`
	StringsCacheSize uint32                 `protobuf:"varint,2,opt,name=strings_cache_size,json=stringsCacheSize,proto3" json:"strings_cache_size,omitempty"`
	PointsBlobSizes  []uint32               `protobuf:"varint,3,rep,packed,name=points_blob_sizes,json=pointsBlobSizes,proto3" json:"points_blob_sizes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheHeader) Reset() {
	*x = CacheHeader{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheHeader) ProtoMessage() {}

func (x *CacheHeader) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheHeader.ProtoReflect.Descriptor instead.
func (*CacheHeader) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheHeader) GetMetadataSize() uint32 {
	if x != nil {
		return x.MetadataSize
	}
	return 0
}

func (x *CacheHeader) GetStringsCacheSize() uint32 {
	if x != nil {
		return x.StringsCacheSize
	}
	return 0
}

func (x *CacheHeader) GetPointsBlobSizes() []uint32 {
	if x != nil {
		return x.PointsBlobSizes
	}
	return nil
}

type CacheMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	DateCreated   string                 `protobuf:"bytes,2,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheMetadata) Reset() {
	*x = CacheMetadata{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheMetadata) ProtoMessage() {}

func (x *CacheMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheMetadata.ProtoReflect.Descriptor instead.
func (*CacheMetadata) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheMetadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CacheMetadata) GetDateCreated() string {
	if x != nil {
		return x.DateCreated
	}
	return ""
}

func (x *CacheMetadata) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type StringsCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streets       []string               `protobuf:"bytes,2,rep,name=streets,proto3" json:"streets,omitempty"`
	Cities        []string               `protobuf:"bytes,3,rep,name=cities,proto3" json:"cities,omitempty"`
	Regions       []string               `protobuf:"bytes,4,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringsCache) Reset() {
	*x = StringsCache{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringsCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringsCache) ProtoMessage() {}

func (x *StringsCache) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringsCache.ProtoReflect.Descriptor instead.
func (*StringsCache) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *StringsCache) GetStreets() []string {
	if x != nil {
		return x.Streets
	}
	return nil
}

func (x *StringsCache) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *StringsCache) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type PointsBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsBlob) Reset() {
	*x = PointsBlob{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsBlob) ProtoMessage() {}

func (x *PointsBlob) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsBlob.ProtoReflect.Descriptor instead.
func (*PointsBlob) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *PointsBlob) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Street        uint32                 `protobuf:"varint,4,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber   string                 `protobuf:"bytes,5,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	City          uint32                 `protobuf:"varint,6,opt,name=city,proto3" json:"city,omitempty"`
	Region        uint32                 `protobuf:"varint,7,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{4}
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Point) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Point) GetStreet() uint32 {
	if x != nil {
		return x.Street
	}
	return 0
}

func (x *Point) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *Point) GetCity() uint32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *Point) GetRegion() uint32 {
	if x != nil {
		return x.Region
	}
	return 0
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\x12cachesaver.save.v1\"\x8c\x01\n" +
	"\vCacheHeader\x12#\n" +
	"\rmetadata_size\x18\x01 \x01(\rR\fmetadataSize\x12,\n" +
	"\x12strings_cache_size\x18\x02 \x01(\rR\x10stringsCacheSize\x12*\n" +
	"\x11points_blob_sizes\x18\x03 \x03(\rR\x0fpointsBlobSizes\"d\n" +
	"\rCacheMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\fdate_created\x18\x02 \x01(\tR\vdateCreated\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"Z\n" +
	"\fStringsCache\x12\x18\n" +
	"\astreets\x18\x02 \x03(\tR\astreets\x12\x16\n" +
	"\x06cities\x18\x03 \x03(\tR\x06cities\x12\x18\n" +
	"\aregions\x18\x04 \x03(\tR\aregions\"?\n" +
	"\n" +
	"PointsBlob\x121\n" +
	"\x06points\x18\x01 \x03(\v2\x19.cachesaver.save.v1.PointR\x06points\"\xbc\x01\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06street\x18\x04 \x01(\rR\x06street\x12!\n" +
	"\fhouse_number\x18\x05 \x01(\tR\vhouseNumber\x12\x12\n" +
	"\x04city\x18\x06 \x01(\rR\x04city\x12\x16\n" +
	"\x06region\x18\a \x01(\rR\x06regionB\rZ\v./saveprotob\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cache_proto_goTypes = []any{
	(*CacheHeader)(nil),   // 0: cachesaver.save.v1.CacheHeader
	(*CacheMetadata)(nil), // 1: cachesaver.save.v1.CacheMetadata
	(*StringsCache)(nil),  // 2: cachesaver.save.v1.StringsCache
	(*PointsBlob)(nil),    // 3: cachesaver.save.v1.PointsBlob
	(*Point)(nil),         // 4: cachesaver.save.v1.Point
}
var file_cache_proto_depIdxs = []int32{
	4, // 0: cachesaver.save.v1.PointsBlob.points:type_name -> cachesaver.save.v1.Point
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
