openapi: "3.0.2"
info:
  title: RGeoCoderApi
  version: "1.0"

paths:
  /rgeocode/address/{lat}/{lon}:
    parameters:
      - name: lat
        in: path
        required: true
        schema:
          type: string
      - name: lon
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        "500":
          description: Server error
        "400":
          description: Bad request
        "204":
          description: Nothing found in location

  /rgeocode/multiaddress:
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: array
                maxItems: 2
                minItems: 2
                description: "[lat, lon]"
                items:
                  type: number
                  format: float64

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Address"
        "500":
          description: Server error
        "400":
          description: Bad request

components:
  schemas:
    Address:
      type: object
      properties:
        name:
          type: string
        street:
          type: string
        house_number:
          type: string
        city:
          type: string
