openapi: "3.0.2"
info:
  title: RGeoCoderApi
  version: "1.0"

paths:
  /rgeocode/address/{lat}/{lon}:
    tags:
      - reverse geocoding
    parameters:
      - name: lat
        in: path
        required: true
        schema:
          type: string
      - name: lon
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get address by coordinates
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        "500":
          description: Server error
        "400":
          description: Bad request
        "204":
          description: Nothing found in location

  /rgeocode/multiaddress:
    tags:
      - reverse geocoding
    get:
      summary: Get multiple addresses with single request
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: array
                maxItems: 2
                minItems: 2
                description: "[lat, lon]"
                items:
                  type: number
                  format: float64

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Address"
        "500":
          description: Server error
        "400":
          description: Bad request
    post:
      summary: Get multiple addresses with single request
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: array
                maxItems: 2
                minItems: 2
                description: "[lat, lon]"
                items:
                  type: number
                  format: float64

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Address"
        "500":
          description: Server error
        "400":
          description: Bad request

  /fgeocode/search:
    tags:
      - forward geocoding
    parameters:
      - name: q
        in: query
        required: true
        description: Query string to search for an address
        schema:
          type: string
    get:
      summary: Get coordinates of found address or zone for a query
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      required:
                        - address_string
                        - point
                        - score
                      properties:
                        address_string:
                          type: string
                        score:
                          type: number
                          description: Score of the match
                          format: float64
                        point:
                          description: Points to the center of found object
                          type: array
                          items:
                            type: number
                            format: float
                          minItems: 2
                          maxItems: 2
                          example: [1.5, 2.0]
                        multipolygon:
                          type: array
                          description: GeoJSON Multipolygon
        "500":
          description: Server error
        "400":
          description: Bad request
        "204":
          description: Nothing found in location

components:
  schemas:
    Address:
      type: object
      properties:
        name:
          type: string
        street:
          type: string
        house_number:
          type: string
        city:
          type: string
        region:
          type: string
        country:
          type: string
